//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remonter.Appdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int id_message { get; set; }
        public int from_id_staff_member { get; set; }
        public int to_id_staff_member { get; set; }
        public string message_content { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
    }
}
