//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remonter.Appdata
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RepairServiceDevEntities : DbContext
    {
        public RepairServiceDevEntities()
            : base("name=RepairServiceDevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<PurchaseList> PurchaseLists { get; set; }
        public virtual DbSet<RepairingDevice> RepairingDevices { get; set; }
        public virtual DbSet<RepairingPart> RepairingParts { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<staff_moving_log> staff_moving_log { get; set; }
        public virtual DbSet<StaffRole> StaffRoles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TransferDevice> TransferDevices { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
