//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remonter.Appdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseList
    {
        public int id_purchase_list { get; set; }
        public string items_to_buy { get; set; }
        public double price { get; set; }
        public string purchase_list_status { get; set; }
    }
}
