//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remonter.Appdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int id_repair_request { get; set; }
        public string content_request { get; set; }
        public string request_status { get; set; }
        public System.DateTime time_request { get; set; }
    }
}
