//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remonter.Appdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.Messages = new HashSet<Message>();
            this.Messages1 = new HashSet<Message>();
            this.RepairingDevices = new HashSet<RepairingDevice>();
            this.staff_moving_log = new HashSet<staff_moving_log>();
        }
    
        public int id_staff_member { get; set; }
        public string name_staff_member { get; set; }
        public string last_name_staff_member { get; set; }
        public System.DateTime time_hired { get; set; }
        public Nullable<System.DateTime> time_fired { get; set; }
        public int id_branch { get; set; }
        public int id_staff_role { get; set; }
        public Nullable<int> id_user { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public string profile_image_path { get; set; }
        public string profile_photo
        {
            get
            {
                if (String.IsNullOrEmpty(profile_image_path) || String.IsNullOrWhiteSpace(profile_image_path))
                {
                    return "/resources/images/profiles-photo/no-picture.png";
                }
                else
                {

                    return "/resources/images/profiles-photo/" + profile_image_path;
                }
            }
        }

        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepairingDevice> RepairingDevices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<staff_moving_log> staff_moving_log { get; set; }
        public virtual StaffRole StaffRole { get; set; }
        public virtual User User { get; set; }
    }
}
