//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remonter.Appdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff_moving_log
    {
        public int id_move { get; set; }
        public int id_staff_member { get; set; }
        public int id_branch { get; set; }
        public System.DateTime time_branch_approach { get; set; }
        public Nullable<System.DateTime> time_branch_come_out { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
